services:
  app:
    build: .
    restart: always
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./downloads:/app/downloads
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./downloads:/downloads
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 